[supervisord]
nodaemon=true

[program:xbee_master]
command=python /app/xbee_master_collect.py --port /dev/ttyUSB0 --baud 115200 --out /app/images --log /app/logs/xbee_master.log --log-bytes 5000000 --log-backups 10 --log-level INFO
directory=/app
autostart=true
autorestart=true
priority=15
stdout_logfile=/app/logs/xbee_master_supervisor.out.log
stderr_logfile=/app/logs/xbee_master_supervisor.err.log

[program:ftp_server]
command=python /app/ftp_server.py
autostart=true
autorestart=true
priority=20
stdout_logfile=/dev/null
stderr_logfile=/dev/null

[program:rtc_sync_once]
directory=/app/tools
command=python /app/tools/rtc_sync.py
autostart=true
autorestart=false
startretries=0
priority=5
stdout_logfile=/dev/null
stderr_logfile=/dev/null

[program:controller_settings]
command=python /app/controller_settings.py
autostart=true
autorestart=true
priority=10
stdout_logfile=/dev/null
stderr_logfile=/dev/null
[program:smtp_server]
command=python /app/email_server.py
autostart=true
autorestart=true
priority=20
stdout_logfile=/dev/null
stderr_logfile=/dev/null

[program:image_uploader]
command=python /app/rest_client.py
autostart=true
autorestart=true
priority=20
stdout_logfile=/dev/null
stderr_logfile=/dev/null

[program:inference_script]
command=python /app/inference.py
autostart=true
autorestart=true
priority=20
stdout_logfile=/dev/null
stderr_logfile=/dev/null

[program:audio_script]
command=python /app/audio.py
autostart=true
autorestart=true
priority=20
stdout_logfile=/dev/null
stderr_logfile=/dev/null

[program:model_update]
command=python /app/model_update.py
autostart=true
autorestart=true
priority=20
stdout_logfile=/dev/null
stderr_logfile=/dev/null
